### ISSUE TITLE
How to output just status and message

### ISSUE THREAD

**Issue by artworkad** [koajs/json-error#31]
From the readme it is not clear to me how to have an error that contains just status and message. I know from postFormat that I can omit fields from the response. But I don't want them to be created in the first place. I have to use `options.format (Function)` to achieve that but how?

**Comment by nfantone** [comment]
Hi, @ArtworkAD. `message` is [a standard property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/prototype) in `Error.prototype`, while `status` is added by the middleware, by default, like so:

``` js
obj.status = err.status || err.statusCode || 500;
```

That said, I didn't quite get your question. You seem to want to have an error such as:

``` json
{
   "message": "This is an error",
   "status": 500
}
```

But then you mention that you "don't want them to be created in the first place". So which is it? Do you want those properties or not?

You have total control over what ends up becoming your `Error`. Just pass in a `format` function as an option:

``` js
let opts = {
  format: (err) => {
    // Change whatever you like on `err`
    return err;
  }
}
app.use(error(opts));
```

**Comment by artworkad** [comment]
@nfantone I want the error to look like

```
{
   "message": "This is an error",
   "status": 500
}
```

instead of 

```
{
   "message": "This is an error",
   "status": 500,
   "stack": ...,
   "type": ...
}
```

What confuses me is that you first introduce https://github.com/koajs/json-error#optionsformat-function and say 

> Defaults to adding the following non-enumerable properties to the output

Second you introduce https://github.com/koajs/json-error#optionspostformat-function where you show how to omit certain fields from the response. 

So it confuses me that there seem to be two kind of ways to modify the error object. While the second approach is clear to me, simply use _.omit to omit certain fields. However the first approach is kind if lacking documentation because I cannot get a grasp on how to customize it.

**Comment by nfantone** [comment]
@ArtworkAD Maybe docs aren't as clear as they could be. Here's the idea: there isn't "two kind of ways" to format the error. There's a _pipe of functions_ that can be used for that. Each one will take as input the output of the last (hence the "pipe"). There are three functions, called in this order:
- `preFormat`
- `format`
- `postFormat`

They actually receive two arguments: the original `err` raised and the object being formatted (the output of the last function). By default (that is, if you don't pass an `options` argument and override one of these attributes), each one does different things. You can read about their purposes on the [README.md](https://github.com/koajs/json-error/blob/develop/README.md). It's basically a granular way of altering the default behaviour.

So, in your scenario, you don't want anything else on the error object apart from `"message"` and `"status"`. You read the docs and find out that the default `format` function [adds those to the error](https://github.com/koajs/json-error/blob/develop/README.md#optionsformat-function). And, like my suggestion on my previous comment, what you need to do is define a custom `format` function on middleware initialization.

Here's the solution:

``` js
let opts = {
  format: (err, obj) => {
    obj.message = err.message || 'Some default error message';
    obj.status = err.status || err.statusCode || 500;
    return obj;
  }
}
app.use(error(opts));
```

I'll take any suggestions on how to make the docs any clearer! PRs are also welcome.

**Comment by nfantone** [comment]
One thing to consider, though: the snippet above will also preserve any _enumerable_ properties on the original thrown error. That gives the flexibility to allow any other middleware to add additional information on their particular errors. I wouldn't recommend leaving those out, but if you don't want _anything at all_ besides `"message"` and `"status"`, you must also override the `preFormat` function and just make it return an empty object. Or avoid using the second argument, `obj`, on your format function and define a new one.

``` js
let opts = {
  format: (err) => {
    let obj = {};
    obj.message = err.message || 'Some default error message';
    obj.status = err.status || err.statusCode || 500;
    return obj;
  }
}
app.use(error(opts));
```

**Comment by artworkad** [comment]
@nfantone thank you for the comprehensive information

**Comment by artworkad** [comment]
@nfantone using the format function you provided I still see the header

`{"headers":{"Access-Control-Allow-Origin":"chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm"},"message":"Payload does not match color schema","status":422}`

So the header is incorporated into the response somewhere in postFormat?

**Comment by nfantone** [comment]
No, `postFormat` is a no-op, by default. Are you sure there is no other middleware running _after_ `json-error` that could potentially add that prop?

Also, did you create a new object in the `format` function, just as in my example above?

**Comment by nfantone** [comment]
@ArtworkAD I have [released 3.1.0](https://www.npmjs.com/package/koa-json-error) that includes a simpler, shorthand option for what you are trying to do.

You now can pass a simple `function` as argument to the middleware and it'll behave as an `options.format` function with no `preFormat` or `postFormat`.

``` js
function formatError(err) {
  let obj = {};
  obj.message = err.message || 'Some default error message';
  obj.status = err.status || err.statusCode || 500;
  return obj;
}
app.use(error(formatError));
```

**Comment by artworkad** [comment]
@nfantone appreciate it. Problem solved!

**Comment by nfantone** [comment]
Glad to hear.
